version: '3.9'
services:
  to_onnx:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
    - 7860:7860
    volumes:
      - ../gradio/:/app/gradio
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
